### ISSUE TITLE
Fails on Fedora 23, UX303

### ISSUE THREAD

**Issue by akaihola** [hanipouspilot/focaltech-dkms#3]
I have an ASUS UX303 running Fedora 23, and I get this:

```
$ git clone git@github.com:hanipouspilot/focaltech-dkms.git
Cloning into 'focaltech-dkms'...
remote: Counting objects: 86, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 86 (delta 19), reused 86 (delta 19), pack-reused 0
Receiving objects: 100% (86/86), 181.89 KiB | 135.00 KiB/s, done.
Resolving deltas: 100% (19/19), done.
Checking connectivity... done.

$ sudo dkms add ./focaltech-dkms
Creating symlink /var/lib/dkms/focaltech/1.5/source ->
                 /usr/src/focaltech-1.5

DKMS: add completed.

$ dkms install -m focaltech -v 1.5
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make KERNELRELEASE=4.3.5-300.fc23.x86_64 -C /lib/modules/4.3.5-300.fc23.x86_64/build M=/var/lib/dkms/focaltech/1.5/build/src psmouse.ko...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.3.5-300.fc23.x86_64 (x86_64)
Consult /var/lib/dkms/focaltech/1.5/build/make.log for more information.

$ cat /var/lib/dkms/focaltech/1.5/build/make.log
DKMS make.log for focaltech-1.5 for kernel 4.3.5-300.fc23.x86_64 (x86_64)
Fri Mar 11 12:53:21 EET 2016
make: Entering directory '/usr/src/kernels/4.3.5-300.fc23.x86_64'
  CC      /var/lib/dkms/focaltech/1.5/build/src/psmouse-base.o
  CC      /var/lib/dkms/focaltech/1.5/build/src/synaptics.o
/var/lib/dkms/focaltech/1.5/build/src/synaptics.c: In function ‘synaptics_profile_sensor_process’:
/var/lib/dkms/focaltech/1.5/build/src/synaptics.c:1310:2: error: too few arguments to function ‘input_mt_assign_slots’
  input_mt_assign_slots(dev, slot, pos, nsemi);
  ^
In file included from /var/lib/dkms/focaltech/1.5/build/src/synaptics.c:29:0:
include/linux/input/mt.h:121:5: note: declared here
 int input_mt_assign_slots(struct input_dev *dev, int *slots,
     ^
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/focaltech/1.5/build/src/synaptics.o' failed
make[1]: *** [/var/lib/dkms/focaltech/1.5/build/src/synaptics.o] Error 1
Makefile:1552: recipe for target 'psmouse.ko' failed
make: *** [psmouse.ko] Error 2
make: Leaving directory '/usr/src/kernels/4.3.5-300.fc23.x86_64'
```

**Comment by hanipouspilot** [comment]
This code will not build for kernel 4.3. It has been merged since kernel 4.2.
If your touchpad does not work, it must be not a Focaltech.

**Comment by pabloab** [comment]
As [told here](https://github.com/vlasenko/hid-asus-dkms/issues/48#issue-218003043) I have also an Asus UX303 with a non working Focaltech touchpad. It respond with `evtest` but not work either way, or work with `proto=imps` but without multitouch. Not sure if related to [this launchpad bug](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1372609?comments=all).
